const fs = require('fs');
const path = require('path');

const localesDir = path.join(__dirname, '../src/locales');

// Define the master filter structure with translations
const filterTranslations = {
    es: {
        clear: "Limpiar Filtros",
        price: "Precio",
        min: "Mín",
        max: "Máx",
        brand: "Marca",
        all_brands: "Todas",
        year: "Año",
        from: "Desde",
        to: "Hasta",
        displacement: "Cilindrada (cc)",
        transmission: "Transmisión",
        all_transmissions: "Todas",
        transmission_manual: "Manual",
        transmission_automatic: "Automática",
        fuel: "Combustible",
        all_fuels: "Todos",
        fuel_gasoline: "Gasolina",
        fuel_diesel: "Diésel",
        fuel_hybrid: "Híbrido",
        fuel_electric: "Eléctrico",
        fuel_lpg: "GLP",
        doors: "Puertas",
        all_doors: "Todas",
        doors_2: "2 puertas",
        doors_3: "3 puertas",
        doors_4: "4 puertas",
        doors_5: "5 puertas",
        color: "Color",
        all_colors: "Todos",
        condition: "Condición",
        all_conditions: "Todas",
        condition_new: "Nuevo",
        condition_used: "Usado"
    },
    en: {
        clear: "Clear Filters",
        price: "Price",
        min: "Min",
        max: "Max",
        brand: "Brand",
        all_brands: "All",
        year: "Year",
        from: "From",
        to: "To",
        displacement: "Displacement (cc)",
        transmission: "Transmission",
        all_transmissions: "All",
        transmission_manual: "Manual",
        transmission_automatic: "Automatic",
        fuel: "Fuel",
        all_fuels: "All",
        fuel_gasoline: "Gasoline",
        fuel_diesel: "Diesel",
        fuel_hybrid: "Hybrid",
        fuel_electric: "Electric",
        fuel_lpg: "LPG",
        doors: "Doors",
        all_doors: "All",
        doors_2: "2 doors",
        doors_3: "3 doors",
        doors_4: "4 doors",
        doors_5: "5 doors",
        color: "Color",
        all_colors: "All",
        condition: "Condition",
        all_conditions: "All",
        condition_new: "New",
        condition_used: "Used"
    },
    zh: {
        clear: "清除筛选",
        price: "价格",
        min: "最低",
        max: "最高",
        brand: "品牌",
        all_brands: "全部",
        year: "年份",
        from: "从",
        to: "到",
        displacement: "排量 (cc)",
        transmission: "变速箱",
        all_transmissions: "全部",
        transmission_manual: "手动",
        transmission_automatic: "自动",
        fuel: "燃料",
        all_fuels: "全部",
        fuel_gasoline: "汽油",
        fuel_diesel: "柴油",
        fuel_hybrid: "混合动力",
        fuel_electric: "电动",
        fuel_lpg: "液化石油气",
        doors: "车门",
        all_doors: "全部",
        doors_2: "2门",
        doors_3: "3门",
        doors_4: "4门",
        doors_5: "5门",
        color: "颜色",
        all_colors: "全部",
        condition: "车况",
        all_conditions: "全部",
        condition_new: "新车",
        condition_used: "二手车"
    },
    ja: {
        clear: "フィルターをクリア",
        price: "価格",
        min: "最小",
        max: "最大",
        brand: "ブランド",
        all_brands: "すべて",
        year: "年式",
        from: "から",
        to: "まで",
        displacement: "排気量 (cc)",
        transmission: "トランスミッション",
        all_transmissions: "すべて",
        transmission_manual: "マニュアル",
        transmission_automatic: "オートマチック",
        fuel: "燃料",
        all_fuels: "すべて",
        fuel_gasoline: "ガソリン",
        fuel_diesel: "ディーゼル",
        fuel_hybrid: "ハイブリッド",
        fuel_electric: "電気",
        fuel_lpg: "LPG",
        doors: "ドア数",
        all_doors: "すべて",
        doors_2: "2ドア",
        doors_3: "3ドア",
        doors_4: "4ドア",
        doors_5: "5ドア",
        color: "色",
        all_colors: "すべて",
        condition: "状態",
        all_conditions: "すべて",
        condition_new: "新車",
        condition_used: "中古車"
    },
    ru: {
        clear: "Сбросить фильтры",
        price: "Цена",
        min: "Мин",
        max: "Макс",
        brand: "Марка",
        all_brands: "Все",
        year: "Год",
        from: "От",
        to: "До",
        displacement: "Объем (см³)",
        transmission: "Коробка передач",
        all_transmissions: "Все",
        transmission_manual: "Механика",
        transmission_automatic: "Автомат",
        fuel: "Топливо",
        all_fuels: "Все",
        fuel_gasoline: "Бензин",
        fuel_diesel: "Дизель",
        fuel_hybrid: "Гибрид",
        fuel_electric: "Электро",
        fuel_lpg: "ГБО",
        doors: "Двери",
        all_doors: "Все",
        doors_2: "2 двери",
        doors_3: "3 двери",
        doors_4: "4 двери",
        doors_5: "5 дверей",
        color: "Цвет",
        all_colors: "Все",
        condition: "Состояние",
        all_conditions: "Все",
        condition_new: "Новый",
        condition_used: "Б/У"
    },
    pt: {
        clear: "Limpar Filtros",
        price: "Preço",
        min: "Mín",
        max: "Máx",
        brand: "Marca",
        all_brands: "Todas",
        year: "Ano",
        from: "De",
        to: "Até",
        displacement: "Cilindrada (cc)",
        transmission: "Transmissão",
        all_transmissions: "Todas",
        transmission_manual: "Manual",
        transmission_automatic: "Automática",
        fuel: "Combustível",
        all_fuels: "Todos",
        fuel_gasoline: "Gasolina",
        fuel_diesel: "Diesel",
        fuel_hybrid: "Híbrido",
        fuel_electric: "Elétrico",
        fuel_lpg: "GPL",
        doors: "Portas",
        all_doors: "Todas",
        doors_2: "2 portas",
        doors_3: "3 portas",
        doors_4: "4 portas",
        doors_5: "5 portas",
        color: "Cor",
        all_colors: "Todas",
        condition: "Condição",
        all_conditions: "Todas",
        condition_new: "Novo",
        condition_used: "Usado"
    },
    fr: {
        clear: "Effacer les filtres",
        price: "Prix",
        min: "Min",
        max: "Max",
        brand: "Marque",
        all_brands: "Toutes",
        year: "Année",
        from: "De",
        to: "À",
        displacement: "Cylindrée (cc)",
        transmission: "Transmission",
        all_transmissions: "Toutes",
        transmission_manual: "Manuelle",
        transmission_automatic: "Automatique",
        fuel: "Carburant",
        all_fuels: "Tous",
        fuel_gasoline: "Essence",
        fuel_diesel: "Diesel",
        fuel_hybrid: "Hybride",
        fuel_electric: "Électrique",
        fuel_lpg: "GPL",
        doors: "Portes",
        all_doors: "Toutes",
        doors_2: "2 portes",
        doors_3: "3 portes",
        doors_4: "4 portes",
        doors_5: "5 portes",
        color: "Couleur",
        all_colors: "Toutes",
        condition: "État",
        all_conditions: "Tous",
        condition_new: "Neuf",
        condition_used: "Occasion"
    },
    de: {
        clear: "Filter zurücksetzen",
        price: "Preis",
        min: "Min",
        max: "Max",
        brand: "Marke",
        all_brands: "Alle",
        year: "Jahr",
        from: "Von",
        to: "Bis",
        displacement: "Hubraum (cc)",
        transmission: "Getriebe",
        all_transmissions: "Alle",
        transmission_manual: "Schaltgetriebe",
        transmission_automatic: "Automatik",
        fuel: "Kraftstoff",
        all_fuels: "Alle",
        fuel_gasoline: "Benzin",
        fuel_diesel: "Diesel",
        fuel_hybrid: "Hybrid",
        fuel_electric: "Elektrisch",
        fuel_lpg: "Autogas (LPG)",
        doors: "Türen",
        all_doors: "Alle",
        doors_2: "2 Türen",
        doors_3: "3 Türen",
        doors_4: "4 Türen",
        doors_5: "5 Türen",
        color: "Farbe",
        all_colors: "Alle",
        condition: "Zustand",
        all_conditions: "Alle",
        condition_new: "Neu",
        condition_used: "Gebraucht"
    },
    it: {
        clear: "Pulisci Filtri",
        price: "Prezzo",
        min: "Min",
        max: "Max",
        brand: "Marca",
        all_brands: "Tutte",
        year: "Anno",
        from: "Da",
        to: "A",
        displacement: "Cilindrata (cc)",
        transmission: "Trasmissione",
        all_transmissions: "Tutte",
        transmission_manual: "Manuale",
        transmission_automatic: "Automatica",
        fuel: "Carburante",
        all_fuels: "Tutti",
        fuel_gasoline: "Benzina",
        fuel_diesel: "Diesel",
        fuel_hybrid: "Ibrida",
        fuel_electric: "Elettrica",
        fuel_lpg: "GPL",
        doors: "Porte",
        all_doors: "Tutte",
        doors_2: "2 porte",
        doors_3: "3 porte",
        doors_4: "4 porte",
        doors_5: "5 porte",
        color: "Colore",
        all_colors: "Tutti",
        condition: "Condizione",
        all_conditions: "Tutte",
        condition_new: "Nuovo",
        condition_used: "Usato"
    },
    ko: {
        clear: "필터 초기화",
        price: "가격",
        min: "최소",
        max: "최대",
        brand: "브랜드",
        all_brands: "전체",
        year: "연식",
        from: "부터",
        to: "까지",
        displacement: "배기량 (cc)",
        transmission: "변속기",
        all_transmissions: "전체",
        transmission_manual: "수동",
        transmission_automatic: "자동",
        fuel: "연료",
        all_fuels: "전체",
        fuel_gasoline: "가솔린",
        fuel_diesel: "디젤",
        fuel_hybrid: "하이브리드",
        fuel_electric: "전기",
        fuel_lpg: "LPG",
        doors: "문",
        all_doors: "전체",
        doors_2: "2도어",
        doors_3: "3도어",
        doors_4: "4도어",
        doors_5: "5도어",
        color: "색상",
        all_colors: "전체",
        condition: "상태",
        all_conditions: "전체",
        condition_new: "신차",
        condition_used: "중고차"
    },
    ar: {
        clear: "مسح الفلاتر",
        price: "السعر",
        min: "أدنى",
        max: "أقصى",
        brand: "الماركة",
        all_brands: "الكل",
        year: "السنة",
        from: "من",
        to: "إلى",
        displacement: "سعة المحرك (cc)",
        transmission: "ناقل الحركة",
        all_transmissions: "الكل",
        transmission_manual: "يدوي",
        transmission_automatic: "أوتوماتيك",
        fuel: "الوقود",
        all_fuels: "الكل",
        fuel_gasoline: "بنزين",
        fuel_diesel: "ديزل",
        fuel_hybrid: "هجين",
        fuel_electric: "كهربائي",
        fuel_lpg: "غاز",
        doors: "الأبواب",
        all_doors: "الكل",
        doors_2: "2 باب",
        doors_3: "3 أبواب",
        doors_4: "4 أبواب",
        doors_5: "5 أبواب",
        color: "اللون",
        all_colors: "الكل",
        condition: "الحالة",
        all_conditions: "الكل",
        condition_new: "جديد",
        condition_used: "مستعمل"
    },
    hi: {
        clear: "फ़िल्टर साफ़ करें",
        price: "कीमत",
        min: "न्यूनतम",
        max: "अधिकतम",
        brand: "ब्रांड",
        all_brands: "सभी",
        year: "वर्ष",
        from: "से",
        to: "तक",
        displacement: "विस्थापन (cc)",
        transmission: "ट्रांसमिशन",
        all_transmissions: "सभी",
        transmission_manual: "मैनुअल",
        transmission_automatic: "ऑटोमैटिक",
        fuel: "ईंधन",
        all_fuels: "सभी",
        fuel_gasoline: "पेट्रोल",
        fuel_diesel: "डीजल",
        fuel_hybrid: "हाइब्रिड",
        fuel_electric: "इलेक्ट्रिक",
        fuel_lpg: "एलपीजी",
        doors: "दरवाजे",
        all_doors: "सभी",
        doors_2: "2 दरवाजे",
        doors_3: "3 दरवाजे",
        doors_4: "4 दरवाजे",
        doors_5: "5 दरवाजे",
        color: "रंग",
        all_colors: "सभी",
        condition: "स्थिति",
        all_conditions: "सभी",
        condition_new: "नई",
        condition_used: "पुरानी"
    },
    tr: {
        clear: "Filtreleri Temizle",
        price: "Fiyat",
        min: "Min",
        max: "Maks",
        brand: "Marka",
        all_brands: "Tümü",
        year: "Yıl",
        from: "Başlangıç",
        to: "Bitiş",
        displacement: "Motor Hacmi (cc)",
        transmission: "Vites",
        all_transmissions: "Tümü",
        transmission_manual: "Manuel",
        transmission_automatic: "Otomatik",
        fuel: "Yakıt",
        all_fuels: "Tümü",
        fuel_gasoline: "Benzin",
        fuel_diesel: "Dizel",
        fuel_hybrid: "Hibrit",
        fuel_electric: "Elektrik",
        fuel_lpg: "LPG",
        doors: "Kapı",
        all_doors: "Tümü",
        doors_2: "2 kapı",
        doors_3: "3 kapı",
        doors_4: "4 kapı",
        doors_5: "5 kapı",
        color: "Renk",
        all_colors: "Tümü",
        condition: "Durum",
        all_conditions: "Tümü",
        condition_new: "Yeni",
        condition_used: "İkinci El"
    },
    nl: {
        clear: "Filters wissen",
        price: "Prijs",
        min: "Min",
        max: "Max",
        brand: "Merk",
        all_brands: "Alle",
        year: "Bouwjaar",
        from: "Van",
        to: "Tot",
        displacement: "Cilinderinhoud (cc)",
        transmission: "Transmissie",
        all_transmissions: "Alle",
        transmission_manual: "Handgeschakeld",
        transmission_automatic: "Automaat",
        fuel: "Brandstof",
        all_fuels: "Alle",
        fuel_gasoline: "Benzine",
        fuel_diesel: "Diesel",
        fuel_hybrid: "Hybride",
        fuel_electric: "Elektrisch",
        fuel_lpg: "LPG",
        doors: "Deuren",
        all_doors: "Alle",
        doors_2: "2 deuren",
        doors_3: "3 deuren",
        doors_4: "4 deuren",
        doors_5: "5 deuren",
        color: "Kleur",
        all_colors: "Alle",
        condition: "Staat",
        all_conditions: "Alle",
        condition_new: "Nieuw",
        condition_used: "Gebruikt"
    },
    pl: {
        clear: "Wyczyść filtry",
        price: "Cena",
        min: "Min",
        max: "Maks",
        brand: "Marka",
        all_brands: "Wszystkie",
        year: "Rok",
        from: "Od",
        to: "Do",
        displacement: "Pojemność (cc)",
        transmission: "Skrzynia biegów",
        all_transmissions: "Wszystkie",
        transmission_manual: "Manualna",
        transmission_automatic: "Automatyczna",
        fuel: "Paliwo",
        all_fuels: "Wszystkie",
        fuel_gasoline: "Benzyna",
        fuel_diesel: "Diesel",
        fuel_hybrid: "Hybryda",
        fuel_electric: "Elektryczny",
        fuel_lpg: "LPG",
        doors: "Drzwi",
        all_doors: "Wszystkie",
        doors_2: "2 drzwi",
        doors_3: "3 drzwi",
        doors_4: "4 drzwi",
        doors_5: "5 drzwi",
        color: "Kolor",
        all_colors: "Wszystkie",
        condition: "Stan",
        all_conditions: "Wszyskie",
        condition_new: "Nowy",
        condition_used: "Używany"
    },
    sv: {
        clear: "Rensa filter",
        price: "Pris",
        min: "Min",
        max: "Max",
        brand: "Märke",
        all_brands: "Alla",
        year: "År",
        from: "Från",
        to: "Till",
        displacement: "Motorvolym (cc)",
        transmission: "Växellåda",
        all_transmissions: "Alla",
        transmission_manual: "Manuell",
        transmission_automatic: "Automat",
        fuel: "Bränsle",
        all_fuels: "Alla",
        fuel_gasoline: "Bensin",
        fuel_diesel: "Diesel",
        fuel_hybrid: "Hybrid",
        fuel_electric: "El",
        fuel_lpg: "LPG",
        doors: "Dörrar",
        all_doors: "Alla",
        doors_2: "2 dörrar",
        doors_3: "3 dörrar",
        doors_4: "4 dörrar",
        doors_5: "5 dörrar",
        color: "Färg",
        all_colors: "Alla",
        condition: "Skick",
        all_conditions: "Alla",
        condition_new: "Ny",
        condition_used: "Begagnad"
    },
    vi: {
        clear: "Xóa bộ lọc",
        price: "Giá",
        min: "Thấp nhất",
        max: "Cao nhất",
        brand: "Hãng xe",
        all_brands: "Tất cả",
        year: "Năm",
        from: "Từ",
        to: "Đến",
        displacement: "Dung tích (cc)",
        transmission: "Hộp số",
        all_transmissions: "Tất cả",
        transmission_manual: "Số sàn",
        transmission_automatic: "Tự động",
        fuel: "Nhiên liệu",
        all_fuels: "Tất cả",
        fuel_gasoline: "Xăng",
        fuel_diesel: "Dầu Diesel",
        fuel_hybrid: "Hybrid",
        fuel_electric: "Điện",
        fuel_lpg: "Mõ",
        doors: "Cửa",
        all_doors: "Tất cả",
        doors_2: "2 cửa",
        doors_3: "3 cửa",
        doors_4: "4 cửa",
        doors_5: "5 cửa",
        color: "Màu sắc",
        all_colors: "Tất cả",
        condition: "Tình trạng",
        all_conditions: "Tất cả",
        condition_new: "Mới",
        condition_used: "Đã qua sử dụng"
    },
    th: {
        clear: "ล้างตัวกรอง",
        price: "ราคา",
        min: "ต่ำสุด",
        max: "สูงสุด",
        brand: "ยี่ห้อ",
        all_brands: "ทั้งหมด",
        year: "ปี",
        from: "จาก",
        to: "ถึง",
        displacement: "ความจุกระบอกสูบ (cc)",
        transmission: "เกียร์",
        all_transmissions: "ทั้งหมด",
        transmission_manual: "ธรรมดา",
        transmission_automatic: "อัตโนมัติ",
        fuel: "เชื้อเพลิง",
        all_fuels: "ทั้งหมด",
        fuel_gasoline: "เบนซิน",
        fuel_diesel: "ดีเซล",
        fuel_hybrid: "ไฮบริด",
        fuel_electric: "ไฟฟ้า",
        fuel_lpg: "LPG",
        doors: "ประตู",
        all_doors: "ทั้งหมด",
        doors_2: "2 ประตู",
        doors_3: "3 ประตู",
        doors_4: "4 ประตู",
        doors_5: "5 ประตู",
        color: "สี",
        all_colors: "ทั้งหมด",
        condition: "สภาพ",
        all_conditions: "ทั้งหมด",
        condition_new: "ใหม่",
        condition_used: "มือสอง"
    },
    id: {
        clear: "Hapus Filter",
        price: "Harga",
        min: "Min",
        max: "Maks",
        brand: "Merek",
        all_brands: "Semua",
        year: "Tahun",
        from: "Dari",
        to: "Sampai",
        displacement: "Kapasitas (cc)",
        transmission: "Transmisi",
        all_transmissions: "Semua",
        transmission_manual: "Manual",
        transmission_automatic: "Otomatis",
        fuel: "Bahan Bakar",
        all_fuels: "Semua",
        fuel_gasoline: "Bensin",
        fuel_diesel: "Diesel",
        fuel_hybrid: "Hibrida",
        fuel_electric: "Listrik",
        fuel_lpg: "LPG",
        doors: "Pintu",
        all_doors: "Semua",
        doors_2: "2 pintu",
        doors_3: "3 pintu",
        doors_4: "4 pintu",
        doors_5: "5 pintu",
        color: "Warna",
        all_colors: "Semua",
        condition: "Kondisi",
        all_conditions: "Semua",
        condition_new: "Baru",
        condition_used: "Bekas"
    },
    he: {
        clear: "נקה מסננים",
        price: "מחיר",
        min: "מינימום",
        max: "מקסימום",
        brand: "מותג",
        all_brands: "הכל",
        year: "שנה",
        from: "מ",
        to: "עד",
        displacement: "נפח מנוע (סמ״ק)",
        transmission: "תיבת הילוכים",
        all_transmissions: "הכל",
        transmission_manual: "ידני",
        transmission_automatic: "אוטומט",
        fuel: "דלק",
        all_fuels: "הכל",
        fuel_gasoline: "בנזין",
        fuel_diesel: "דיזל",
        fuel_hybrid: "היברידי",
        fuel_electric: "חשמלי",
        fuel_lpg: "גז",
        doors: "דלתות",
        all_doors: "הכל",
        doors_2: "2 דלתות",
        doors_3: "3 דלתות",
        doors_4: "4 דלתות",
        doors_5: "5 דלתות",
        color: "צבע",
        all_colors: "הכל",
        condition: "מצב",
        all_conditions: "הכל",
        condition_new: "חדש",
        condition_used: "משומש"
    },
    ur: {
        clear: "فلٹر صاف کریں",
        price: "قیمت",
        min: "کم سے کم",
        max: "زیادہ سے زیادہ",
        brand: "برانڈ",
        all_brands: "تمام",
        year: "سال",
        from: "سے",
        to: "تک",
        displacement: "انجن کا حجم (cc)",
        transmission: "ٹرانسمیشن",
        all_transmissions: "تمام",
        transmission_manual: "مینول",
        transmission_automatic: "آٹومیٹک",
        fuel: "ایندھن",
        all_fuels: "تمام",
        fuel_gasoline: "پیٹرول",
        fuel_diesel: "ڈیزل",
        fuel_hybrid: "ہائبرڈ",
        fuel_electric: "الیکٹرک",
        fuel_lpg: "ایل پی جی",
        doors: "دروازے",
        all_doors: "تمام",
        doors_2: "2 دروازے",
        doors_3: "3 دروازے",
        doors_4: "4 دروازے",
        doors_5: "5 دروازے",
        color: "رنگ",
        all_colors: "تمام",
        condition: "حالت",
        all_conditions: "تمام",
        condition_new: "نیا",
        condition_used: "استعمال شدہ"
    }
};

fs.readdir(localesDir, (err, files) => {
    if (err) {
        console.error("Could not list directory:", err);
        return;
    }

    files.forEach(file => {
        if (!file.endsWith('.json')) return;
        const langCode = file.replace('.json', '');
        const filePath = path.join(localesDir, file);

        console.log(`Processing filters for ${langCode}...`);

        try {
            const content = fs.readFileSync(filePath, 'utf8');
            const json = JSON.parse(content);
            const masterFilters = filterTranslations[langCode] || filterTranslations.en;

            // Ensure market object exists
            if (!json.market) json.market = {};

            // Overwrite or create persistent 'filters' object
            // User requested "everything", so we upgrade the schema to match ES
            json.market.filters = masterFilters;

            // Ensure other keys used in filters exist
            if (!json.market.filters_label) json.market.filters_label = masterFilters.clear.replace('Clear ', '').replace('Limpiar ', '').replace('Cari', 'Filters'); // Simple fallback for label if needed

            fs.writeFileSync(filePath, JSON.stringify(json, null, 4));
            console.log(`✅ Updated filters in ${langCode}`);
        } catch (e) {
            console.error(`❌ Error processing ${langCode}:`, e);
        }
    });

    console.log("Global market filters synchronization complete!");
});
